### ISSUE TITLE
migration crash

### ISSUE THREAD

**Issue by JaSei** [JaSei/storage-s3-migrator#2]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x709b15]

goroutine 8 [running]:
github.com/avast/storage-s3-migrator/s3.Hs3Client.doRequestClosedBody.func1(0xc4232ad680, 0xc4232ad688)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/s3/s3.go:188 +0x25
github.com/avast/storage-s3-migrator/s3.Hs3Client.doRequestClosedBody(0xc4207d8080, 0x7ffdff4e3737, 0x7, 0xc420e0e010, 0x10, 0xc420e18020, 0x20, 0x9c9440, 0xa01cc0, 0x0, ...)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/s3/s3.go:193 +0xe7
github.com/avast/storage-s3-migrator/s3.Hs3Client.UploadObject(0xc4207d8080, 0x7ffdff4e3737, 0x7, 0xc420e0e010, 0x10, 0xc420e18020, 0x20, 0x9c9440, 0xa01cc0, 0x0, ...)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/s3/s3.go:98 +0x7cb
main.main.func1.1.2(0x9d3500, 0xc420e201f0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:64 +0xaf
github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go.PathImpl.Visit.func1(0xc42a24a3f0, 0x63, 0x9d0320, 0xc4274c01a0, 0x0, 0x0, 0x0, 0x0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go/visit.go:25 +0xc7
path/filepath.walk(0xc42a24a3f0, 0x63, 0x9d0320, 0xc4274c01a0, 0xc420174e70, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:356 +0x81
path/filepath.walk(0xc420e16520, 0x1e, 0x9d0320, 0xc423c02270, 0xc420174e70, 0x0, 0x30)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.Walk(0xc420e16520, 0x1e, 0xc420174e70, 0x9d0320, 0xc423c021a0)
        /usr/lib/golang/src/path/filepath/path.go:403 +0x11d
github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go.PathImpl.Visit(0xc420e16520, 0x1e, 0xc4200b4100, 0xc4200b4100)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go/visit.go:30 +0x97
github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go.(*PathImpl).Visit(0xc420178350, 0xc4200b4100, 0xc420130000)
        <autogenerated>:1 +0x58
main.main.func1.1(0x9d3500, 0xc420178350)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:62 +0x182
main.byteRange.visitTree(0xc420163f20, 0x9d3500, 0xc420050ef0, 0xc4232adf20)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/visittree.go:31 +0x1a8
main.main.func1(0xc4200167d0, 0x9d3500, 0xc420050ef0, 0xc420130000, 0x1, 0xc4200c3f20)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:53 +0x1ab
created by main.main
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:47 +0x2ed
```

**Comment by JaSei** [comment]
fixed by b816778
