### ISSUE TITLE
migration crash

### ISSUE THREAD

**Issue by JaSei** [JaSei/storage-s3-migrator#3]
```
time="2018-04-07T16:28:19+02:00" level=info msg="Path /data/storage/Samples/E4/B5/A4/E4B5A4BBA3AFB8D5D658F58FB7FAB97FF000ECB51A05CA82D4B7CBA7A5028419.dat already inserted"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x4d9495]

goroutine 12 [running]:
github.com/avast/storage-s3-migrator/vendor/github.com/pkg/errors.(*fundamental).Error(0x0, 0x0, 0x0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/vendor/github.com/pkg/errors/errors.go:124 +0x5
main.main.func1.1.2.3(0x0, 0x9cbe00, 0x0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:81 +0x42
github.com/avast/storage-s3-migrator/vendor/github.com/avast/retry-go.Do(0xc4232ad8e8, 0xc4232ad8c8, 0x2, 0x2, 0x10, 0xc4200187a0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/vendor/github.com/avast/retry-go/retry.go:90 +0x1c5
main.main.func1.1.2(0x9d6540, 0xc54e609590)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:73 +0x344
github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go.PathImpl.Visit.func1(0xc5504fcb60, 0x63, 0x9d3360, 0xc429ab9930, 0x0, 0x0, 0x0, 0x0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go/visit.go:25 +0xc7
path/filepath.walk(0xc5504fcb60, 0x63, 0x9d3360, 0xc429ab9930, 0xc4201280c0, 0x0, 0x0)
        /usr/lib/golang/src/path/filepath/path.go:356 +0x81
path/filepath.walk(0xc4232bd060, 0x1e, 0x9d3360, 0xc421f7c4e0, 0xc4201280c0, 0x0, 0x30)
        /usr/lib/golang/src/path/filepath/path.go:381 +0x3a0
path/filepath.Walk(0xc4232bd060, 0x1e, 0xc4201280c0, 0x9d3360, 0xc421f7c410)
        /usr/lib/golang/src/path/filepath/path.go:403 +0x11d
github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go.PathImpl.Visit(0xc4232bd060, 0x1e, 0xc420d58b40, 0xc420d58b00)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go/visit.go:30 +0x97
github.com/avast/storage-s3-migrator/vendor/github.com/JaSei/pathutil-go.(*PathImpl).Visit(0xc420d4bb50, 0xc420d58b40, 0xc420110000)
        <autogenerated>:1 +0x58
main.main.func1.1(0x9d6540, 0xc420d4bb50)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:65 +0x1b6
main.byteRange.visitTree(0xc42003bfa0, 0x9d6540, 0xc42003ef10, 0xc4232adf10)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/visittree.go:31 +0x1a8
main.main.func1(0xc420014800, 0x9d6540, 0xc42003ef10, 0xc420110000, 0xc42003ef00, 0x5, 0xbfa0)
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:56 +0x1c7
created by main.main
        /home/seidl/golang_workspace/src/github.com/avast/storage-s3-migrator/main.go:50 +0x36c
```

**Comment by JaSei** [comment]
should be fixed by #2
